services:
  - type: web
    name: free-traffic-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: "10000"
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: TOKEN_SECRET
        sync: false
      - key: ADMIN_KEY
        sync: false
